version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - "/data/db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  # # Uncomment to bring up Mongo web portal 
  # mongo-express:
  #   image: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}

  react-frontend:
    build: frontend
    restart: unless-stopped
    container_name: directory-frontend
    ports:
      - 3000:3000
    environment:
      REACT_APP_NODE_URL: ${REACT_APP_NODE_URL}
    
  node-express-backend:
    build: backend
    restart: unless-stopped
    container_name: directory-backend
    ports:
      - 4000:4000
    depends_on:
      - mongo
    environment:
      MONGO_URL: ${MONGO_URL}